//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModuleExam.Classes.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam_Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exam_Books()
        {
            this.Exam_BookSale = new HashSet<Exam_BookSale>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string Genre { get; set; }
        public string Author { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> CountInShop { get; set; }
        public Nullable<int> CountInStore { get; set; }
        public string Description { get; set; }
        public string Cover { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exam_BookSale> Exam_BookSale { get; set; }
    }
}
